packages:
  - packages/*
  - packages/shared/*
  - packages/features/*/service
  - packages/features/*/ui
  - packages/personal/*/service
  - packages/personal/*/ui
  - apps/*

catalog:
  '@actual-app/api': ^25.12.0
  '@babel/preset-env': ^7.28.5
  '@babel/preset-flow': ^7.27.1
  '@babel/preset-react': ^7.28.5
  '@babel/preset-typescript': ^7.28.5
  '@expo/vector-icons': ^15.0.3
  '@react-native-async-storage/async-storage': ^2.2.0
  '@react-navigation/bottom-tabs': ^7.4.0
  '@react-navigation/elements': ^2.6.3
  '@react-navigation/native': ^7.1.8
  '@testing-library/react-native': ^13.3.3
  '@types/jest': ^30.0.0
  '@types/react': ~19.1.10
  babel-jest: ^30.2.0
  bcrypt: ^5.1.1
  cors: ^2.8.5
  dinero.js: ^1.9.1
  dotenv: ^16.3.1
  eslint: ^9.25.0
  eslint-config-expo: ~10.0.0
  expo: ~54.0.30
  expo-constants: ~18.0.12
  expo-font: ~14.0.10
  expo-haptics: ~15.0.8
  expo-image: ~3.0.11
  expo-linking: ~8.0.11
  expo-router: ~6.0.21
  expo-splash-screen: ~31.0.13
  expo-status-bar: ~3.0.9
  expo-symbols: ~1.0.8
  expo-system-ui: ~6.0.9
  expo-web-browser: ~15.0.10
  expo-build-properties: ~0.12.5
  express: ^4.18.2
  googleapis: ^169.0.0
  helmet: ^7.1.0
  jest: ^30.2.0
  jest-environment-jsdom: ^30.2.0
  js-yaml: ^4.1.1
  jsonwebtoken: ^9.0.2
  nodemon: ^3.0.2
  openai: ^4.24.0
  pg: ^8.11.3
  pnpm: ^10.26.2
  react: 19.1.0
  react-dom: 19.1.0
  react-native: ^0.81.5
  react-native-gesture-handler: ~2.28.0
  react-native-reanimated: ~4.1.1
  react-native-safe-area-context: 5.6.2
  react-native-screens: ~4.16.0
  react-native-web: ^0.21.0
  react-native-worklets: ^0.5.1
  react-test-renderer: 19.1.0
  supertest: ^7.1.4
  swagger-ui-express: ^5.0.0
  typescript: ~5.9.2
  uuid: ^9.0.1
  winston: ^3.11.0
  yamljs: ^0.3.0
