/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Smart Pocket Server API
 * API for Smart Pocket personal finance management system.
Homeserver deployment model - each instance serves one user.

 * OpenAPI spec version: 0.1.0
 */
import { httpClient } from './httpClient';
export type ErrorDetails = { [key: string]: unknown };

export interface Error {
  error: string;
  message: string;
  details?: ErrorDetails;
}

export type ServerInfoFeatures = {
  /** Whether Google Sheets sync feature is enabled */
  googleSheetsSync?: boolean;
  /** Whether AI spending insights are enabled */
  aiInsights?: boolean;
};

export interface ServerInfo {
  version?: string;
  features?: ServerInfoFeatures;
  /** Default currency for this server */
  currency?: string;
}

export interface OCRRequest {
  /** Base64-encoded receipt image */
  image: string;
}

export interface OCRResponse {
  /** Raw OCR extracted text from receipt */
  ocrText?: string;
  /** OCR confidence score (0-1) */
  confidence?: number;
  /** Processing time in milliseconds */
  processingTime?: number;
}

export interface OCRParseRequest {
  /** Raw OCR text to parse */
  ocrText: string;
  /** User's notes about OCR issues or context */
  remarks?: string;
}

export interface ParsedTransaction {
  merchant?: string;
  date?: string;
  total?: number;
  currency?: string;
  items?: ParsedItem[];
  /** AI parsing confidence score (0-1) */
  confidence?: number;
}

export interface ParsedItem {
  /** Store-specific product code from receipt */
  codeName?: string;
  readableName?: string;
  price?: number;
  quantity?: number;
  currency?: string;
}

export type TransactionCreateOcrMetadata = {
  /** Original OCR text */
  rawText?: string;
  /** User's remarks about OCR quality */
  remarks?: string;
  confidence?: number;
};

export interface TransactionCreate {
  date: string;
  payeeId: string;
  accountId: string;
  currency?: string;
  items: LineItemCreate[];
  ocrMetadata?: TransactionCreateOcrMetadata;
}

export interface LineItemCreate {
  codeName: string;
  readableName: string;
  price: number;
  quantity: number;
  currency?: string;
}

export interface Transaction {
  id?: string;
  date?: string;
  payee?: Payee;
  account?: Account;
  total?: number;
  currency?: string;
  items?: LineItem[];
  /** ID of synced transaction in Actual Budget */
  actualBudgetId?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface LineItem {
  id?: string;
  codeName?: string;
  readableName?: string;
  price?: number;
  quantity?: number;
  currency?: string;
}

export interface Payee {
  id?: string;
  name?: string;
  /** Number of transactions with this payee */
  transactionCount?: number;
}

export interface Account {
  id?: string;
  name?: string;
  /** Linked Actual Budget account ID */
  actualBudgetId?: string;
}

export interface ItemCodeSuggestion {
  codeName?: string;
  readableName?: string;
  /** Number of times this code has been used */
  frequency?: number;
  lastUsed?: string;
  /** Merchants where this code was seen */
  associatedPayees?: string[];
}

export interface Price {
  /** Decimal value as string for exact precision */
  amount: string;
  /**
   * ISO 4217 currency code
   * @minLength 3
   * @maxLength 3
   */
  currency: string;
}

/**
 * - withdraw: Bank → Cash
- transfer: Bank ↔ Bank/eWallet
- deposit: Cash → Bank/eWallet

 */
export type TransferType = typeof TransferType[keyof typeof TransferType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransferType = {
  withdraw: 'withdraw',
  transfer: 'transfer',
  deposit: 'deposit',
} as const;

export interface TransferCreate {
  date: string;
  transferType: TransferType;
  fromAccountId: string;
  toAccountId: string;
  amount: Price;
  fee?: Price;
  /** Whether transfer has a fee */
  hasFee: boolean;
  /** Required for withdraw/deposit, optional for transfer */
  atmPayeeId?: string;
  notes?: string;
}

export interface Transfer {
  id?: string;
  date?: string;
  transferType?: TransferType;
  fromAccountId?: string;
  fromAccountName?: string;
  toAccountId?: string;
  toAccountName?: string;
  amount?: Price;
  fee?: Price;
  atmPayeeId?: string;
  atmPayeeName?: string;
  /** ID of synced transaction in Actual Budget */
  actualBudgetId?: string;
  notes?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface TransferList {
  transfers?: Transfer[];
  total?: number;
  limit?: number;
  offset?: number;
}

export type GetHealth200 = {
  status?: string;
};

export type PostApiV1ConnectBodyDeviceInfo = {
  /** Client platform (iOS, Android, web) */
  platform: string;
  appVersion: string;
  deviceId: string;
};

export type PostApiV1ConnectBody = {
  deviceInfo: PostApiV1ConnectBodyDeviceInfo;
};

export type PostApiV1Connect200 = {
  /** JWT bearer token for subsequent requests */
  token: string;
  /** Token expiration in seconds (default 30 days) */
  expiresIn: number;
  serverInfo: ServerInfo;
};

export type PostApiV1Disconnect200 = {
  success?: boolean;
  message?: string;
};

export type GetApiV1TransactionsParams = {
limit?: number;
offset?: number;
startDate?: string;
endDate?: string;
payeeId?: string;
};

export type GetApiV1Transactions200 = {
  transactions?: Transaction[];
  total?: number;
  limit?: number;
  offset?: number;
};

export type GetApiV1TransfersParams = {
limit?: number;
offset?: number;
startDate?: string;
endDate?: string;
};

export type GetApiV1PayeesParams = {
/**
 * Search payee names
 */
search?: string;
};

export type GetApiV1Payees200 = {
  payees?: Payee[];
};

export type PostApiV1PayeesBody = {
  name: string;
};

export type GetApiV1Accounts200 = {
  accounts?: Account[];
};

export type GetApiV1ProductsSearchParams = {
/**
 * Partial code name or readable name
 */
query: string;
/**
 * Filter by payee/merchant context
 */
payeeId?: string;
limit?: number;
};

export type GetApiV1ProductsSearch200 = {
  suggestions?: ItemCodeSuggestion[];
};

export type PostApiV1GoogleSheetsSyncDraft200PendingChangesItemClearedCurrent = {
  amount?: string;
  currency?: string;
};

export type PostApiV1GoogleSheetsSyncDraft200PendingChangesItemClearedSynced = {
  amount?: string;
  currency?: string;
};

export type PostApiV1GoogleSheetsSyncDraft200PendingChangesItemCleared = {
  current?: PostApiV1GoogleSheetsSyncDraft200PendingChangesItemClearedCurrent;
  synced?: PostApiV1GoogleSheetsSyncDraft200PendingChangesItemClearedSynced;
};

/**
 * @nullable
 */
export type PostApiV1GoogleSheetsSyncDraft200PendingChangesItemUncleared = { [key: string]: unknown } | null;

export type PostApiV1GoogleSheetsSyncDraft200PendingChangesItem = {
  accountId?: string;
  accountName?: string;
  cleared?: PostApiV1GoogleSheetsSyncDraft200PendingChangesItemCleared;
  /** @nullable */
  uncleared?: PostApiV1GoogleSheetsSyncDraft200PendingChangesItemUncleared;
};

export type PostApiV1GoogleSheetsSyncDraft200Summary = {
  totalAccounts?: number;
  totalChanges?: number;
};

export type PostApiV1GoogleSheetsSyncDraft200 = {
  draftId?: string;
  createdAt?: string;
  pendingChanges?: PostApiV1GoogleSheetsSyncDraft200PendingChangesItem[];
  summary?: PostApiV1GoogleSheetsSyncDraft200Summary;
};

export type PostApiV1GoogleSheetsSyncApproveDraftId200 = {
  success?: boolean;
  syncedAt?: string;
  accountsSynced?: number;
  spreadsheetUrl?: string;
};

/**
 * @summary Health check
 */
export type getHealthResponse200 = {
  data: GetHealth200
  status: 200
}
    
export type getHealthResponseSuccess = (getHealthResponse200) & {
  headers: Headers;
};
;

export type getHealthResponse = (getHealthResponseSuccess)

export const getGetHealthUrl = () => {


  

  return `/health`
}

export const getHealth = async ( options?: RequestInit): Promise<getHealthResponse> => {
  
  return httpClient<getHealthResponse>(getGetHealthUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Exchange API key for bearer token (JWT).
First stage of two-stage authentication.

 * @summary Connect and get bearer token
 */
export type postApiV1ConnectResponse200 = {
  data: PostApiV1Connect200
  status: 200
}

export type postApiV1ConnectResponse401 = {
  data: Error
  status: 401
}
    
export type postApiV1ConnectResponseSuccess = (postApiV1ConnectResponse200) & {
  headers: Headers;
};
export type postApiV1ConnectResponseError = (postApiV1ConnectResponse401) & {
  headers: Headers;
};

export type postApiV1ConnectResponse = (postApiV1ConnectResponseSuccess | postApiV1ConnectResponseError)

export const getPostApiV1ConnectUrl = () => {


  

  return `/api/v1/connect`
}

export const postApiV1Connect = async (postApiV1ConnectBody: PostApiV1ConnectBody, options?: RequestInit): Promise<postApiV1ConnectResponse> => {
  
  return httpClient<postApiV1ConnectResponse>(getPostApiV1ConnectUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1ConnectBody,)
  }
);}



/**
 * Invalidate bearer token and end session.
User must reconnect with API key to get new token.

 * @summary Disconnect session
 */
export type postApiV1DisconnectResponse200 = {
  data: PostApiV1Disconnect200
  status: 200
}

export type postApiV1DisconnectResponse401 = {
  data: Error
  status: 401
}
    
export type postApiV1DisconnectResponseSuccess = (postApiV1DisconnectResponse200) & {
  headers: Headers;
};
export type postApiV1DisconnectResponseError = (postApiV1DisconnectResponse401) & {
  headers: Headers;
};

export type postApiV1DisconnectResponse = (postApiV1DisconnectResponseSuccess | postApiV1DisconnectResponseError)

export const getPostApiV1DisconnectUrl = () => {


  

  return `/api/v1/disconnect`
}

export const postApiV1Disconnect = async ( options?: RequestInit): Promise<postApiV1DisconnectResponse> => {
  
  return httpClient<postApiV1DisconnectResponse>(getPostApiV1DisconnectUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



/**
 * Uses OpenAI to extract transaction details from OCR text
 * @summary Parse OCR text into structured transaction data
 */
export type postApiV1OcrParseResponse200 = {
  data: ParsedTransaction
  status: 200
}

export type postApiV1OcrParseResponse400 = {
  data: Error
  status: 400
}
    
export type postApiV1OcrParseResponseSuccess = (postApiV1OcrParseResponse200) & {
  headers: Headers;
};
export type postApiV1OcrParseResponseError = (postApiV1OcrParseResponse400) & {
  headers: Headers;
};

export type postApiV1OcrParseResponse = (postApiV1OcrParseResponseSuccess | postApiV1OcrParseResponseError)

export const getPostApiV1OcrParseUrl = () => {


  

  return `/api/v1/ocr/parse`
}

export const postApiV1OcrParse = async (oCRParseRequest: OCRParseRequest, options?: RequestInit): Promise<postApiV1OcrParseResponse> => {
  
  return httpClient<postApiV1OcrParseResponse>(getPostApiV1OcrParseUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      oCRParseRequest,)
  }
);}



/**
 * @summary List transactions
 */
export type getApiV1TransactionsResponse200 = {
  data: GetApiV1Transactions200
  status: 200
}
    
export type getApiV1TransactionsResponseSuccess = (getApiV1TransactionsResponse200) & {
  headers: Headers;
};
;

export type getApiV1TransactionsResponse = (getApiV1TransactionsResponseSuccess)

export const getGetApiV1TransactionsUrl = (params?: GetApiV1TransactionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/transactions?${stringifiedParams}` : `/api/v1/transactions`
}

export const getApiV1Transactions = async (params?: GetApiV1TransactionsParams, options?: RequestInit): Promise<getApiV1TransactionsResponse> => {
  
  return httpClient<getApiV1TransactionsResponse>(getGetApiV1TransactionsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Creates transaction, stores in PostgreSQL, and syncs to Actual Budget
 * @summary Create transaction
 */
export type postApiV1TransactionsResponse201 = {
  data: Transaction
  status: 201
}

export type postApiV1TransactionsResponse400 = {
  data: Error
  status: 400
}
    
export type postApiV1TransactionsResponseSuccess = (postApiV1TransactionsResponse201) & {
  headers: Headers;
};
export type postApiV1TransactionsResponseError = (postApiV1TransactionsResponse400) & {
  headers: Headers;
};

export type postApiV1TransactionsResponse = (postApiV1TransactionsResponseSuccess | postApiV1TransactionsResponseError)

export const getPostApiV1TransactionsUrl = () => {


  

  return `/api/v1/transactions`
}

export const postApiV1Transactions = async (transactionCreate: TransactionCreate, options?: RequestInit): Promise<postApiV1TransactionsResponse> => {
  
  return httpClient<postApiV1TransactionsResponse>(getPostApiV1TransactionsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      transactionCreate,)
  }
);}



/**
 * @summary Get transaction by ID
 */
export type getApiV1TransactionsIdResponse200 = {
  data: Transaction
  status: 200
}

export type getApiV1TransactionsIdResponse404 = {
  data: Error
  status: 404
}
    
export type getApiV1TransactionsIdResponseSuccess = (getApiV1TransactionsIdResponse200) & {
  headers: Headers;
};
export type getApiV1TransactionsIdResponseError = (getApiV1TransactionsIdResponse404) & {
  headers: Headers;
};

export type getApiV1TransactionsIdResponse = (getApiV1TransactionsIdResponseSuccess | getApiV1TransactionsIdResponseError)

export const getGetApiV1TransactionsIdUrl = (id: string,) => {


  

  return `/api/v1/transactions/${id}`
}

export const getApiV1TransactionsId = async (id: string, options?: RequestInit): Promise<getApiV1TransactionsIdResponse> => {
  
  return httpClient<getApiV1TransactionsIdResponse>(getGetApiV1TransactionsIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Update transaction
 */
export type putApiV1TransactionsIdResponse200 = {
  data: Transaction
  status: 200
}

export type putApiV1TransactionsIdResponse404 = {
  data: Error
  status: 404
}
    
export type putApiV1TransactionsIdResponseSuccess = (putApiV1TransactionsIdResponse200) & {
  headers: Headers;
};
export type putApiV1TransactionsIdResponseError = (putApiV1TransactionsIdResponse404) & {
  headers: Headers;
};

export type putApiV1TransactionsIdResponse = (putApiV1TransactionsIdResponseSuccess | putApiV1TransactionsIdResponseError)

export const getPutApiV1TransactionsIdUrl = (id: string,) => {


  

  return `/api/v1/transactions/${id}`
}

export const putApiV1TransactionsId = async (id: string,
    transactionCreate: TransactionCreate, options?: RequestInit): Promise<putApiV1TransactionsIdResponse> => {
  
  return httpClient<putApiV1TransactionsIdResponse>(getPutApiV1TransactionsIdUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      transactionCreate,)
  }
);}



/**
 * @summary Delete transaction
 */
export type deleteApiV1TransactionsIdResponse204 = {
  data: void
  status: 204
}

export type deleteApiV1TransactionsIdResponse404 = {
  data: Error
  status: 404
}
    
export type deleteApiV1TransactionsIdResponseSuccess = (deleteApiV1TransactionsIdResponse204) & {
  headers: Headers;
};
export type deleteApiV1TransactionsIdResponseError = (deleteApiV1TransactionsIdResponse404) & {
  headers: Headers;
};

export type deleteApiV1TransactionsIdResponse = (deleteApiV1TransactionsIdResponseSuccess | deleteApiV1TransactionsIdResponseError)

export const getDeleteApiV1TransactionsIdUrl = (id: string,) => {


  

  return `/api/v1/transactions/${id}`
}

export const deleteApiV1TransactionsId = async (id: string, options?: RequestInit): Promise<deleteApiV1TransactionsIdResponse> => {
  
  return httpClient<deleteApiV1TransactionsIdResponse>(getDeleteApiV1TransactionsIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}



/**
 * @summary List transfers
 */
export type getApiV1TransfersResponse200 = {
  data: TransferList
  status: 200
}
    
export type getApiV1TransfersResponseSuccess = (getApiV1TransfersResponse200) & {
  headers: Headers;
};
;

export type getApiV1TransfersResponse = (getApiV1TransfersResponseSuccess)

export const getGetApiV1TransfersUrl = (params?: GetApiV1TransfersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/transfers?${stringifiedParams}` : `/api/v1/transfers`
}

export const getApiV1Transfers = async (params?: GetApiV1TransfersParams, options?: RequestInit): Promise<getApiV1TransfersResponse> => {
  
  return httpClient<getApiV1TransfersResponse>(getGetApiV1TransfersUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Creates transfer between accounts, stores in PostgreSQL, and syncs to Actual Budget
 * @summary Create transfer transaction
 */
export type postApiV1TransfersResponse201 = {
  data: Transfer
  status: 201
}

export type postApiV1TransfersResponse400 = {
  data: Error
  status: 400
}
    
export type postApiV1TransfersResponseSuccess = (postApiV1TransfersResponse201) & {
  headers: Headers;
};
export type postApiV1TransfersResponseError = (postApiV1TransfersResponse400) & {
  headers: Headers;
};

export type postApiV1TransfersResponse = (postApiV1TransfersResponseSuccess | postApiV1TransfersResponseError)

export const getPostApiV1TransfersUrl = () => {


  

  return `/api/v1/transfers`
}

export const postApiV1Transfers = async (transferCreate: TransferCreate, options?: RequestInit): Promise<postApiV1TransfersResponse> => {
  
  return httpClient<postApiV1TransfersResponse>(getPostApiV1TransfersUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      transferCreate,)
  }
);}



/**
 * @summary Get transfer by ID
 */
export type getApiV1TransfersIdResponse200 = {
  data: Transfer
  status: 200
}

export type getApiV1TransfersIdResponse404 = {
  data: Error
  status: 404
}
    
export type getApiV1TransfersIdResponseSuccess = (getApiV1TransfersIdResponse200) & {
  headers: Headers;
};
export type getApiV1TransfersIdResponseError = (getApiV1TransfersIdResponse404) & {
  headers: Headers;
};

export type getApiV1TransfersIdResponse = (getApiV1TransfersIdResponseSuccess | getApiV1TransfersIdResponseError)

export const getGetApiV1TransfersIdUrl = (id: string,) => {


  

  return `/api/v1/transfers/${id}`
}

export const getApiV1TransfersId = async (id: string, options?: RequestInit): Promise<getApiV1TransfersIdResponse> => {
  
  return httpClient<getApiV1TransfersIdResponse>(getGetApiV1TransfersIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary List all payees
 */
export type getApiV1PayeesResponse200 = {
  data: GetApiV1Payees200
  status: 200
}
    
export type getApiV1PayeesResponseSuccess = (getApiV1PayeesResponse200) & {
  headers: Headers;
};
;

export type getApiV1PayeesResponse = (getApiV1PayeesResponseSuccess)

export const getGetApiV1PayeesUrl = (params?: GetApiV1PayeesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/payees?${stringifiedParams}` : `/api/v1/payees`
}

export const getApiV1Payees = async (params?: GetApiV1PayeesParams, options?: RequestInit): Promise<getApiV1PayeesResponse> => {
  
  return httpClient<getApiV1PayeesResponse>(getGetApiV1PayeesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Create new payee
 */
export type postApiV1PayeesResponse201 = {
  data: Payee
  status: 201
}

export type postApiV1PayeesResponse400 = {
  data: Error
  status: 400
}
    
export type postApiV1PayeesResponseSuccess = (postApiV1PayeesResponse201) & {
  headers: Headers;
};
export type postApiV1PayeesResponseError = (postApiV1PayeesResponse400) & {
  headers: Headers;
};

export type postApiV1PayeesResponse = (postApiV1PayeesResponseSuccess | postApiV1PayeesResponseError)

export const getPostApiV1PayeesUrl = () => {


  

  return `/api/v1/payees`
}

export const postApiV1Payees = async (postApiV1PayeesBody: PostApiV1PayeesBody, options?: RequestInit): Promise<postApiV1PayeesResponse> => {
  
  return httpClient<postApiV1PayeesResponse>(getPostApiV1PayeesUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1PayeesBody,)
  }
);}



/**
 * @summary List all accounts
 */
export type getApiV1AccountsResponse200 = {
  data: GetApiV1Accounts200
  status: 200
}
    
export type getApiV1AccountsResponseSuccess = (getApiV1AccountsResponse200) & {
  headers: Headers;
};
;

export type getApiV1AccountsResponse = (getApiV1AccountsResponseSuccess)

export const getGetApiV1AccountsUrl = () => {


  

  return `/api/v1/accounts`
}

export const getApiV1Accounts = async ( options?: RequestInit): Promise<getApiV1AccountsResponse> => {
  
  return httpClient<getApiV1AccountsResponse>(getGetApiV1AccountsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Auto-suggest products based on partial code/name and historical usage
 * @summary Get product suggestions
 */
export type getApiV1ProductsSearchResponse200 = {
  data: GetApiV1ProductsSearch200
  status: 200
}
    
export type getApiV1ProductsSearchResponseSuccess = (getApiV1ProductsSearchResponse200) & {
  headers: Headers;
};
;

export type getApiV1ProductsSearchResponse = (getApiV1ProductsSearchResponseSuccess)

export const getGetApiV1ProductsSearchUrl = (params: GetApiV1ProductsSearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/products/search?${stringifiedParams}` : `/api/v1/products/search`
}

export const getApiV1ProductsSearch = async (params: GetApiV1ProductsSearchParams, options?: RequestInit): Promise<getApiV1ProductsSearchResponse> => {
  
  return httpClient<getApiV1ProductsSearchResponse>(getGetApiV1ProductsSearchUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Get pending account balance changes that need to be synced to Google Sheets.
Creates a draft with the changes that can be reviewed before syncing.
Personal feature - only available if GOOGLE_SHEETS_ENABLED=true on server.

 * @summary Create sync draft
 */
export type postApiV1GoogleSheetsSyncDraftResponse200 = {
  data: PostApiV1GoogleSheetsSyncDraft200
  status: 200
}

export type postApiV1GoogleSheetsSyncDraftResponse404 = {
  data: Error
  status: 404
}
    
export type postApiV1GoogleSheetsSyncDraftResponseSuccess = (postApiV1GoogleSheetsSyncDraftResponse200) & {
  headers: Headers;
};
export type postApiV1GoogleSheetsSyncDraftResponseError = (postApiV1GoogleSheetsSyncDraftResponse404) & {
  headers: Headers;
};

export type postApiV1GoogleSheetsSyncDraftResponse = (postApiV1GoogleSheetsSyncDraftResponseSuccess | postApiV1GoogleSheetsSyncDraftResponseError)

export const getPostApiV1GoogleSheetsSyncDraftUrl = () => {


  

  return `/api/v1/google-sheets/sync/draft`
}

export const postApiV1GoogleSheetsSyncDraft = async ( options?: RequestInit): Promise<postApiV1GoogleSheetsSyncDraftResponse> => {
  
  return httpClient<postApiV1GoogleSheetsSyncDraftResponse>(getPostApiV1GoogleSheetsSyncDraftUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



/**
 * Execute the Google Sheets sync using a previously created draft.
Updates the Google Sheets with current account balances from Actual Budget.
Personal feature - only available if GOOGLE_SHEETS_ENABLED=true on server.

 * @summary Execute sync
 */
export type postApiV1GoogleSheetsSyncApproveDraftIdResponse200 = {
  data: PostApiV1GoogleSheetsSyncApproveDraftId200
  status: 200
}

export type postApiV1GoogleSheetsSyncApproveDraftIdResponse400 = {
  data: Error
  status: 400
}

export type postApiV1GoogleSheetsSyncApproveDraftIdResponse404 = {
  data: Error
  status: 404
}
    
export type postApiV1GoogleSheetsSyncApproveDraftIdResponseSuccess = (postApiV1GoogleSheetsSyncApproveDraftIdResponse200) & {
  headers: Headers;
};
export type postApiV1GoogleSheetsSyncApproveDraftIdResponseError = (postApiV1GoogleSheetsSyncApproveDraftIdResponse400 | postApiV1GoogleSheetsSyncApproveDraftIdResponse404) & {
  headers: Headers;
};

export type postApiV1GoogleSheetsSyncApproveDraftIdResponse = (postApiV1GoogleSheetsSyncApproveDraftIdResponseSuccess | postApiV1GoogleSheetsSyncApproveDraftIdResponseError)

export const getPostApiV1GoogleSheetsSyncApproveDraftIdUrl = (draftId: string,) => {


  

  return `/api/v1/google-sheets/sync/approve/${draftId}`
}

export const postApiV1GoogleSheetsSyncApproveDraftId = async (draftId: string, options?: RequestInit): Promise<postApiV1GoogleSheetsSyncApproveDraftIdResponse> => {
  
  return httpClient<postApiV1GoogleSheetsSyncApproveDraftIdResponse>(getPostApiV1GoogleSheetsSyncApproveDraftIdUrl(draftId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}
